name: "Discord announce"
description: "Post a message in discord"
branding:
  icon: "anchor"
  color: "blue"

inputs:
  WEBHOOK:
    description: "Discord webhook"
    required: true
  CONTENT:
    description: "Message you want to send"
    required: false
  EMBEDS:
    description: "boolen to indicate you want to send embeds. Not a normal text"
    required: false
  TITLE:
    description: "title foe the embeds"
    required: false
  ANDROID_RESULT:
    description: "android build result"
    required: false
  IOS_RESULT:
    description: "ios build result"
    required: false
  CHANGELOG:
    description: "change logs link"
    required: false
  RELEASE_VERSION:
    description: "version that is going to release"
    required: false

runs:
  using: node20
  main: dist/index.js
